# Generated by Django 5.2.3 on 2025-07-29 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vege", "0004_department_studentid_receipe_recipe_view_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="vege.department",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_profile",
                to="vege.studentid",
            ),
        ),
    ]
