# Generated by Django 5.2.3 on 2025-08-01 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vege", "0005_alter_student_department_alter_student_student_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="student_age",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(18),
                    django.core.validators.MaxValueValidator(30),
                ],
            ),
        ),
    ]
