# Generated by Django 5.2.3 on 2025-07-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food2", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="instructions",
            field=models.TextField(default="", max_length=300),
        ),
        migrations.AddField(
            model_name="recipe",
            name="ngredients",
            field=models.TextField(default="", max_length=300),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="description",
            field=models.TextField(max_length=300),
        ),
    ]
