# Generated by Django 5.2.3 on 2025-07-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food2", "0004_recipe_instructions_recipe_ngredients_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_name", models.CharField(max_length=100)),
                ("car_speed", models.IntegerField(default=60)),
                ("car_color", models.CharField(max_length=20)),
                ("car_model", models.IntegerField()),
                ("car_brand", models.CharField(default="Unknown", max_length=50)),
            ],
        ),
    ]
