# Generated by Django 5.2.3 on 2025-07-22 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vege", "0002_category_alter_receipe_options_receipe_author_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="receipe",
            old_name="author",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="receipe",
            name="cook_time",
        ),
        migrations.RemoveField(
            model_name="receipe",
            name="meal_type",
        ),
        migrations.RemoveField(
            model_name="receipe",
            name="prep_time",
        ),
        migrations.RemoveField(
            model_name="receipe",
            name="servings",
        ),
    ]
