# Generated by Django 5.2.3 on 2025-08-11 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vege", "0007_subject_subjectsmarks"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subjectsmarks",
            options={"verbose_name": "Subject Mark"},
        ),
        migrations.RenameField(
            model_name="subjectsmarks",
            old_name="Subject",
            new_name="subject",
        ),
        migrations.AlterUniqueTogether(
            name="subjectsmarks",
            unique_together={("student", "subject")},
        ),
    ]
