# Generated by Django 5.2.3 on 2025-09-11 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vege", "0008_alter_subjectsmarks_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_rank", models.PositiveIntegerField()),
                ("date_reportcard_issued", models.DateField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="studentreportcards",
                        to="vege.student",
                    ),
                ),
            ],
        ),
    ]
