# Generated by Django 5.2.3 on 2025-09-12 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vege", "0009_reportcard"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reportcard",
            options={
                "ordering": ["-date_reportcard_issued"],
                "verbose_name": "Report Card",
            },
        ),
        migrations.AlterUniqueTogether(
            name="reportcard",
            unique_together={("student_rank", "date_reportcard_issued")},
        ),
    ]
