# Generated by Django 5.2.3 on 2025-09-12 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vege", "0010_alter_reportcard_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportcard",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reportcards",
                to="vege.student",
            ),
        ),
    ]
