# Generated by Django 5.2.3 on 2025-09-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vege", "0011_alter_reportcard_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipe",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
