# Generated by Django 5.2.3 on 2025-09-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vege", "0012_receipe_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
