# Generated by Django 5.2.3 on 2025-09-26 16:28

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vege", "0013_student_is_deleted"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={
                "default_manager_name": "admin_objects",
                "ordering": ["student_name"],
                "verbose_name": "student",
            },
        ),
        migrations.AlterModelManagers(
            name="student",
            managers=[
                ("admin_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="receipe",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
