# Generated by Django 5.2.3 on 2025-09-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vege", "0014_alter_student_options_alter_student_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipe",
            name="slugs",
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
