# Generated by Django 5.2.3 on 2025-06-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipe_name", models.CharField(max_length=255)),
                ("recipe_description", models.TextField()),
                ("recipe_ingredients", models.TextField()),
                ("recipe_instructions", models.TextField()),
                ("recipe_image", models.ImageField(upload_to="recipes/images/")),
                ("recipe_prep_time", models.IntegerField()),
                ("recipe_cook_time", models.IntegerField()),
            ],
            options={
                "verbose_name_plural": "Recipes",
            },
        ),
    ]
